git:
   depth: 16777215
language: c

compiler:
    - gcc

install:
    - sudo apt-get install gawk make cmake libfuse-dev fuse user-mode-linux
    - sudo mknod /dev/fuse c 10 229
    - sudo chmod 666 /dev/fuse
    - cmake .
    - make VERBOSE=1

before_script:
    # Version of some utils
    - bash --version
    - awk --version
    - dd --version
    - make --version
    - cmake --version

script:
   - ./umltest.sh

branches:
    only:
        - master

