git:
   depth: 16777215
language: c

compiler:
    - gcc

before_script:
    - sudo apt-get install gawk make cmake libfuse-dev fuse
    # Version of some utils
    - bash --version
    - awk --version
    - dd --version
    - make --version
    - cmake --version

script:
    - cmake .
    - make VERBOSE=1
    - make runtests VERBOSE=1

branches:
    only:
        - master

